### ISSUE TITLE
GPT(ft)+Strategy

### ISSUE THREAD

**Issue by nullgogo** [TissueC/PsyQA#1]
您好，关于您论文6.3节中模型的输入和输出，请问在实际对话应用的时候，模型回复的内容会带有各个策略的标签么？

**Comment by TissueC** [comment]
模型直接的生成是会带有标签的。在后处理时可以去掉，或用自然语言进行替换。

**Comment by nullgogo** [comment]
感觉很新颖，比 [ESC](https://github.com/thu-coai/Emotional-Support-Conversation) 返回的策略更丰富。
还有一个疑问，模型生成的各个策略 和 策略对应的回复内容 会不一致么？比如回复的内容是Direct-Guidance相关的，但对应的策略是【Interpretation】或者其他的策略？
后期有考虑开源论文中的代码吗？很有价值，想学习一下。

**Comment by TissueC** [comment]
会有不一致的情况，我们进行了评测，并在论文里进行了汇报（CTRB in Table 6)。
